// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: hVrCe6QR8zQ6ffGdoxKcVS
// Component: 4-9yALJPYUc4pn

import * as React from "react";

import {
  Link,
  GatsbyLinkProps as LinkProps,
  navigate as __gatsbyNavigate
} from "gatsby";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: D9uunrQkdXFQl-/component

import "@plasmicapp/react-web/lib/plasmic.css";

import * as plasmic_new_habistack_com_css from "../new_habistack_com/plasmic_new_habistack_com.module.css"; // plasmic-import: rcEGNgTfxT6W6gDjnxsJgN/projectcss
import * as plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic_library_plasmic_color_type.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import * as plasmic_habistack_marketing_css from "../habistack_marketing/plasmic_habistack_marketing.module.css"; // plasmic-import: cEHjHBABazmDxgQhPGAjL/projectcss
import * as plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import * as projectcss from "./plasmic_v_2_fathym_platform_marketing.module.css"; // plasmic-import: hVrCe6QR8zQ6ffGdoxKcVS/projectcss
import * as sty from "./PlasmicSolutions.module.css"; // plasmic-import: 4-9yALJPYUc4pn/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: GUOtKPWmDowxLy/icon
import ArrowRightsvgIcon from "./icons/PlasmicIcon__ArrowRightsvg"; // plasmic-import: eN0P76-AqjUE47/icon
import logisticsCardpng2EH3QC0ZaeqC4 from "./images/logisticsCardpng.png"; // plasmic-import: -2eH3qC0ZaeqC4/picture
import eventCardpngDIpAgIkfUvgHqt from "./images/eventCardpng.png"; // plasmic-import: dIpAgIKFUvgHqt/picture
import movementCardpng24H6IGSdEFsu from "./images/movementCardpng.png"; // plasmic-import: 24h6iG-SdE_FSU/picture
import agricultureCardpngFuCxPqUgTa6Qas from "./images/agricultureCardpng.png"; // plasmic-import: fuCXPqUgTa6qas/picture
import energyCardpngYtnIxIzyIwP5Fp from "./images/energyCardpng.png"; // plasmic-import: YtnIXIzyIwP5fp/picture
import droneCardpngPiCjtOyxIquqcZ from "./images/droneCardpng.png"; // plasmic-import: PICjtOYXIquqcZ/picture

export type PlasmicSolutions__VariantMembers = {};
export type PlasmicSolutions__VariantsArgs = {};
type VariantPropType = keyof PlasmicSolutions__VariantsArgs;
export const PlasmicSolutions__VariantProps = new Array<VariantPropType>();

export type PlasmicSolutions__ArgsType = {};
type ArgPropType = keyof PlasmicSolutions__ArgsType;
export const PlasmicSolutions__ArgProps = new Array<ArgPropType>();

export type PlasmicSolutions__OverridesType = {
  root?: p.Flex<"section">;
  h2?: p.Flex<"h2">;
};

export interface DefaultSolutionsProps {
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicSolutions__RenderFunc(props: {
  variants: PlasmicSolutions__VariantsArgs;
  args: PlasmicSolutions__ArgsType;
  overrides: PlasmicSolutions__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});

  return (
    <section
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_new_habistack_com_css.plasmic_tokens,
        plasmic_library_plasmic_color_type_css.plasmic_tokens,
        plasmic_habistack_marketing_css.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.root
      )}
    >
      <div className={classNames(projectcss.all, sty.column__rncmu)}>
        <h2
          data-plasmic-name={"h2"}
          data-plasmic-override={overrides.h2}
          className={classNames(
            projectcss.all,
            projectcss.h2,
            projectcss.__wab_text,
            sty.h2
          )}
        >
          {"This text was changed for the platform page"}
        </h2>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__pd5Ng
          )}
        >
          {
            "Bringing overwhelming technology to even the most basic of competitive battles,\nour data can solve your problems today."
          }
        </div>
        <div className={classNames(projectcss.all, sty.columns___4Kubb)}>
          <div className={classNames(projectcss.all, sty.column__nqD3)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__hF9Ot)}
              displayHeight={"230px" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"auto" as const}
              loading={"lazy" as const}
              src={{
                src: logisticsCardpng2EH3QC0ZaeqC4,
                fullWidth: 850,
                fullHeight: 375,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.columns__p42Ev)}>
              <div className={classNames(projectcss.all, sty.column__fUb7S)}>
                <h4
                  className={classNames(
                    projectcss.all,
                    projectcss.h4,
                    projectcss.__wab_text,
                    sty.h4__hKee2
                  )}
                >
                  {"Logistics"}
                </h4>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__lfF
                  )}
                >
                  {"Supply Chain"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___4CuVz
                  )}
                >
                  {
                    "Choke points and bottle necks don't need unexpected interruptions. Much more than alerts, this is integrated intelligence.\n"
                  }
                </div>
                {true ? (
                  <Button
                    className={classNames("__wab_instance", sty.button__cViGp)}
                    color={"softBlue" as const}
                    endIcon={
                      <ArrowRightsvgIcon
                        className={classNames(projectcss.all, sty.svg__y8SMp)}
                        role={"img"}
                      />
                    }
                    shape={"rounded" as const}
                    showEndIcon={true}
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__iJeof
                      )}
                    >
                      {"READ MORE"}
                    </div>
                  </Button>
                ) : null}
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.column__huoxh)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img___2L6Ln)}
              displayHeight={"230px" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"auto" as const}
              loading={"lazy" as const}
              src={{
                src: eventCardpngDIpAgIkfUvgHqt,
                fullWidth: 850,
                fullHeight: 375,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.columns__prlTb)}>
              <div className={classNames(projectcss.all, sty.column__o8Mvg)}>
                <h4
                  className={classNames(
                    projectcss.all,
                    projectcss.h4,
                    projectcss.__wab_text,
                    sty.h4___7YukX
                  )}
                >
                  {"Events"}
                </h4>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ps9Ov
                  )}
                >
                  {"Concerts & Sports"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__oyW8
                  )}
                >
                  {
                    "Corridors flooded with people? Let's make sure rain and floods don't interrupt. With our help the show will go on.\n"
                  }
                </div>
                {true ? (
                  <Button
                    className={classNames("__wab_instance", sty.button__iu5Pe)}
                    color={"softBlue" as const}
                    endIcon={
                      <ArrowRightsvgIcon
                        className={classNames(projectcss.all, sty.svg__c1KDe)}
                        role={"img"}
                      />
                    }
                    shape={"rounded" as const}
                    showEndIcon={true}
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__kOwVi
                      )}
                    >
                      {"READ MORE"}
                    </div>
                  </Button>
                ) : null}
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.column__dkg7)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__q576B)}
              displayHeight={"230px" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"auto" as const}
              loading={"lazy" as const}
              src={{
                src: movementCardpng24H6IGSdEFsu,
                fullWidth: 850,
                fullHeight: 375,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.columns__ncMsP)}>
              <div className={classNames(projectcss.all, sty.column__pA308)}>
                <h4
                  className={classNames(
                    projectcss.all,
                    projectcss.h4,
                    projectcss.__wab_text,
                    sty.h4__jhFod
                  )}
                >
                  {"Movement"}
                </h4>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___2LYIh
                  )}
                >
                  {"Transportation"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__pkThK
                  )}
                >
                  {
                    "The wheel might be where it all started but it's not where we're going. Now we need real intelligent tech to keep everything rolling."
                  }
                </div>
                {true ? (
                  <Button
                    className={classNames("__wab_instance", sty.button__qenf)}
                    color={"softBlue" as const}
                    endIcon={
                      <ArrowRightsvgIcon
                        className={classNames(projectcss.all, sty.svg__mYw3R)}
                        role={"img"}
                      />
                    }
                    shape={"rounded" as const}
                    showEndIcon={true}
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ar2C
                      )}
                    >
                      {"READ MORE"}
                    </div>
                  </Button>
                ) : null}
              </div>
            </div>
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.columns__mfBw)}>
          <div className={classNames(projectcss.all, sty.column___74HSv)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__kFoOo)}
              displayHeight={"230px" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"auto" as const}
              loading={"lazy" as const}
              src={{
                src: agricultureCardpngFuCxPqUgTa6Qas,
                fullWidth: 850,
                fullHeight: 375,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.columns__nxPmE)}>
              <div className={classNames(projectcss.all, sty.column__wuJmH)}>
                <h4
                  className={classNames(
                    projectcss.all,
                    projectcss.h4,
                    projectcss.__wab_text,
                    sty.h4__doXzu
                  )}
                >
                  {"Resources"}
                </h4>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__xiKaD
                  )}
                >
                  {"Agriculture & Mining"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___1ZuCa
                  )}
                >
                  {
                    "Money doesn't grow on trees but it'll certainly fall off of them if they don't make it through the storm. We also help with gold digging. ;)"
                  }
                </div>
                {true ? (
                  <Button
                    className={classNames("__wab_instance", sty.button__dxOOz)}
                    color={"softBlue" as const}
                    endIcon={
                      <ArrowRightsvgIcon
                        className={classNames(projectcss.all, sty.svg___9Lvey)}
                        role={"img"}
                      />
                    }
                    shape={"rounded" as const}
                    showEndIcon={true}
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__w2IyJ
                      )}
                    >
                      {"READ MORE"}
                    </div>
                  </Button>
                ) : null}
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.column__yO5Gi)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img___3LRoD)}
              displayHeight={"230px" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"auto" as const}
              loading={"lazy" as const}
              src={{
                src: energyCardpngYtnIxIzyIwP5Fp,
                fullWidth: 850,
                fullHeight: 375,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.columns__a7L8G)}>
              <div className={classNames(projectcss.all, sty.column__jfv2S)}>
                <h4
                  className={classNames(
                    projectcss.all,
                    projectcss.h4,
                    projectcss.__wab_text,
                    sty.h4__jvJtc
                  )}
                >
                  {"Energy"}
                </h4>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__mhx3
                  )}
                >
                  {"Energy Outlook"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__rxLmP
                  )}
                >
                  {
                    "Solar. Wind. Rain. Fire. The elements may help us make power but they can also disrupt its generation. We keep eyes on it.\n"
                  }
                </div>
                {true ? (
                  <Button
                    className={classNames("__wab_instance", sty.button__gjEo6)}
                    color={"softBlue" as const}
                    endIcon={
                      <ArrowRightsvgIcon
                        className={classNames(projectcss.all, sty.svg__lbYh3)}
                        role={"img"}
                      />
                    }
                    shape={"rounded" as const}
                    showEndIcon={true}
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__zAEf0
                      )}
                    >
                      {"READ MORE"}
                    </div>
                  </Button>
                ) : null}
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.column__v8ZGh)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__xxhn)}
              displayHeight={"230px" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"auto" as const}
              loading={"lazy" as const}
              src={{
                src: droneCardpngPiCjtOyxIquqcZ,
                fullWidth: 850,
                fullHeight: 375,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.columns__hy8M0)}>
              <div className={classNames(projectcss.all, sty.column__piuGw)}>
                <h4
                  className={classNames(
                    projectcss.all,
                    projectcss.h4,
                    projectcss.__wab_text,
                    sty.h4__ymiUi
                  )}
                >
                  {"Robots"}
                </h4>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__cxDgf
                  )}
                >
                  {"They're Coming"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ugRLw
                  )}
                >
                  {
                    "They're here today. Drones and self-driving vehicles may be getting smarter but they still need help navigating the weather."
                  }
                </div>
                {true ? (
                  <Button
                    className={classNames("__wab_instance", sty.button__lFoou)}
                    color={"softBlue" as const}
                    endIcon={
                      <ArrowRightsvgIcon
                        className={classNames(projectcss.all, sty.svg__bZlxX)}
                        role={"img"}
                      />
                    }
                    shape={"rounded" as const}
                    showEndIcon={true}
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___8HyH
                      )}
                    >
                      {"READ MORE"}
                    </div>
                  </Button>
                ) : null}
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "h2"],
  h2: ["h2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "section";
  h2: "h2";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSolutions__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSolutions__VariantsArgs;
    args?: PlasmicSolutions__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicSolutions__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicSolutions__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicSolutions__ArgProps,
          internalVariantPropNames: PlasmicSolutions__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSolutions__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSolutions";
  } else {
    func.displayName = `PlasmicSolutions.${nodeName}`;
  }
  return func;
}

export const PlasmicSolutions = Object.assign(
  // Top-level PlasmicSolutions renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    h2: makeNodeComponent("h2"),

    // Metadata about props expected for PlasmicSolutions
    internalVariantProps: PlasmicSolutions__VariantProps,
    internalArgProps: PlasmicSolutions__ArgProps
  }
);

export default PlasmicSolutions;
/* prettier-ignore-end */
